### ISSUE TITLE
Does not work for absolute file paths

### ISSUE THREAD

**Issue by qgustavor** [ClaudiuCeia/dhash#2]
Due to `join` being used [here](https://github.com/ClaudiuCeia/dhash/blob/982e8f478ddb0e373578401717fa11a4bef41597/src/dhash.ts#L12) instead of using `resolve`.

**Comment by qgustavor** [comment]
Also it can generate hashes with 15 or less characters due to `parseInt(out.join(""), 2).toString(16)`. I will add a fix for that in the same pull request.

**Comment by ClaudiuCeia** [comment]
Awesome, thanks @qgustavor !

**Comment by ClaudiuCeia** [comment]
I'll publish a new version - are you using this in a real project or were you just browsing?

**Comment by qgustavor** [comment]
I'm using it to deduplicate photos in a database for a government backed project.

**Comment by ClaudiuCeia** [comment]
That sounds great! Any chance I can mention that in the README?

**Comment by qgustavor** [comment]
That's fine. I only have the Instagram page of the project at the moment, the website is still in the works: https://www.instagram.com/pddugyn/ (I guess they removed all posts due to electoral laws requiring it since we will vote for a new mayor in October, so the city hall must not use their socials).
